version: '3.6'

services:
  interceptor:
    image: "stabback/interceptor:master"
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mongo
      
  mongo:
    image: mongo:4.1.8-xenial
    restart: unless-stopped
    env_file: ../.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:  
      - dbdata:/data/db  
      

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: