version: '3.6'

services:
  mongo-express:
    image: mongo-express
    networks: 
      - app-network
    ports:
      - "8081:8081"
    env_file: ../.env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD