# Useful during development of Interceptor.  Will live reload with local files when run with the development stack

FROM node:12-alpine

RUN pwd

WORKDIR /home/node/app

COPY package.json .
COPY yarn.lock .
COPY tsconfig.json .

RUN yarn install --frozen-lockfile

EXPOSE 8080